imports = {
  lighttouch-base = "lighttouch-base/",
  lighttouch-logging = "packages/lighttouch-logging",
  lighttouch-json-interface = "packages/lighttouch-json-interface",
  lighttouch-html-interface = "packages/lighttouch-html-interface",
  homepage-package = "packages/homepage-package",
  base-theme = "themes/base-theme",
  send-file-package = "packages/send-file-package",
  lighttouch-change-management = "packages/lighttouch-change-management"
}

lighttouch-base = {
  url = "https://github.com/foundpatterns/lighttouch-base",
  recursive = true
}

lighttouch-logging = {
  url = "https://github.com/foundpatterns/lighttouch-logging"
}

lighttouch-json-interface = {
  url = "https://github.com/foundpatterns/lighttouch-json-interface"
}

lighttouch-html-interface = {
  url = "https://github.com/foundpatterns/lighttouch-html-interface"
}

homepage-package = {
  url = "https://github.com/foundpatterns/base-theme"
}

base-theme = {
  url = "https://github.com/foundpatterns/homepage-package"
}

send-file-package = {
  url = "https://github.com/foundpatterns/send-file-package"
}

lighttouch-change-management = {
  url = "https://github.com/foundpatterns/lighttouch-change-management"
}
