APP_STORE_URL = "https://github.com/foundpatterns/app-store"
PACKAGES_LIST = "packages.scl"
APP_STORE_PATH = os.getenv("HOME") .. "/.mp/packages/"

APP_STORE = "/usr/share/"
APP_STORE_BIN = "/usr/share/bin"

MP_PATH = "/usr/share/mp/"

# What is the relevancy of the following ?
DEFAULT_PATH           = "./"
DEFAULT_SAVE_DIRECTORY = ".mp/"

# SCL file keys
URL       = "url"
RECURSIVE = "recursive"
EXPORT    = "export"
PLUCK     = "pluck"
REPO      = "repo"
LOCAL_IMPORT = "local_import"
